### ISSUE TITLE
Why this project when MSBuild has a built-in way to do the same?

### ISSUE THREAD

**Issue by atifaziz** [springcomp/dotnet-make#1]
It seems that MSBuild already has a built-in way to do what this project does. See “[How to: Build incrementally](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-incrementally)”:

> To enable incremental builds (builds in which only those targets that have not been built before or targets that are out of date, are rebuilt), the Microsoft Build Engine (MSBuild) can compare the timestamps of the input files with the timestamps of the output files and determine whether to skip, build, or partially rebuild a target.

It would be good explain, in the `README`, the unique value of this project.

**Comment by springcomp** [comment]
Thank you for your feedback.

This project was a quick (and dirty) way of doing what I needed. It is used in the [JmesPath.Net](https://github.com/jdevillard/JmesPath.Net) [project file](https://github.com/jdevillard/JmesPath.Net/blob/master/src/jmespath.net/jmespath.net.csproj#L29-L30) where we create a set of C# source files from a couple of Lex/Yacc grammar files using the [GPLEX](https://github.com/Oleg1cqa/gplex) and [GPGG](https://github.com/Oleg1cqa/gpgg) tools.

When using the tools directly, I was not able to build incrementally. With this project, it worked.

I would very much appreciate if you pointed me to a document or helped me doing this in a more correct way.
